language: node_js
node_js:
  - "10.11.0"
cache:
  directories:
    - "node_modules"
before_install:
  - chmod +x build.sh
install:
  - npm i
script:
  - npm start
after_success:
- .travis/push.sh

branches:
  only:
  - master

